[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "PyStochasticVolatility"
version = "1.1"
description = "Financial library created to give support the book Malliavin Calculus and Stochastic Volatility."
readme = "README.md"
requires-python = ">=3.11,<3.12"

authors = [{ name = "David Garcia Lorite", email = "david.garcia.lorite@gmail.com" }, ]

license = { text = "Apache-2.0" }

dependencies = [
  "numpy>=1.26,<1.27",
  "numba>=0.59,<0.60",
  "scipy>=1.10,<1.11",
  "numba-scipy==0.4.0",
  "matplotlib>=3.8",
  "pandas>=2.1",
  "statsmodels>=0.14",
  "QuantLib>=1.36",
  "tabulate>=0.9",
  "prettytable>=3.10",
  "sympy>=1.12",
  "sobol-seq>=0.2.0",
  "py_vollib>=1.0.1",
]

[project.urls]
Homepage = "https://github.com/Dagalon/PyStochasticVolatility"

[tool.setuptools.packages.find]
include = ["*"]
exclude = ["dist", "build", "*.egg-info"]