[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "PyStochasticVolatility"
version = "1.1"
description = "Financial library created to give support the book Malliavin Calculus and Stochastic Volatility."
readme = "README.md"
requires-python = ">=3.8"
authors = [
  { name = "David Garcia Lorite", email = "david.garcia.lorite@gmail.com" },
]
license = { text = "Apache-2.0" }
dependencies = [
  "numpy~=1.21.5",
  "numba~=0.55.1",
  "scipy~=1.7.3",
  "matplotlib~=3.5.1",
  "pandas~=1.4.2",
  "statsmodels~=0.13.2",
  "quantlib~=1.27",
  "tabulate~=0.8.9",
  "prettytable~=3.3.0",
  "sympy~=1.10.1",
  "ncephes~=1.1.0",
]

[project.urls]
Homepage = "https://github.com/Dagalon/PyStochasticVolatility"

[tool.setuptools.packages.find]
include = ["*"]
exclude = ["dist", "build", "*.egg-info"]
